/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated/deliveries'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1DeliveryPartnersIndexRouteImport } from './routes/api/v1/delivery-partners/index'
import { Route as ApiV1AttendanceIndexRouteImport } from './routes/api/v1/attendance/index'
import { Route as ApiV1DeliveryPartnersIdRouteImport } from './routes/api/v1/delivery-partners/$id'
import { Route as ApiV1AttendanceTodayRouteImport } from './routes/api/v1/attendance/today'
import { Route as ApiV1AttendanceCheckOutRouteImport } from './routes/api/v1/attendance/check-out'
import { Route as ApiV1AttendanceCheckInRouteImport } from './routes/api/v1/attendance/check-in'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeliveryPartnersIndexRoute =
  ApiV1DeliveryPartnersIndexRouteImport.update({
    id: '/api/v1/delivery-partners/',
    path: '/api/v1/delivery-partners/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AttendanceIndexRoute = ApiV1AttendanceIndexRouteImport.update({
  id: '/api/v1/attendance/',
  path: '/api/v1/attendance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DeliveryPartnersIdRoute = ApiV1DeliveryPartnersIdRouteImport.update({
  id: '/api/v1/delivery-partners/$id',
  path: '/api/v1/delivery-partners/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AttendanceTodayRoute = ApiV1AttendanceTodayRouteImport.update({
  id: '/api/v1/attendance/today',
  path: '/api/v1/attendance/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AttendanceCheckOutRoute = ApiV1AttendanceCheckOutRouteImport.update({
  id: '/api/v1/attendance/check-out',
  path: '/api/v1/attendance/check-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AttendanceCheckInRoute = ApiV1AttendanceCheckInRouteImport.update({
  id: '/api/v1/attendance/check-in',
  path: '/api/v1/attendance/check-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/attendance/check-in': typeof ApiV1AttendanceCheckInRoute
  '/api/v1/attendance/check-out': typeof ApiV1AttendanceCheckOutRoute
  '/api/v1/attendance/today': typeof ApiV1AttendanceTodayRoute
  '/api/v1/delivery-partners/$id': typeof ApiV1DeliveryPartnersIdRoute
  '/api/v1/attendance/': typeof ApiV1AttendanceIndexRoute
  '/api/v1/delivery-partners/': typeof ApiV1DeliveryPartnersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/attendance/check-in': typeof ApiV1AttendanceCheckInRoute
  '/api/v1/attendance/check-out': typeof ApiV1AttendanceCheckOutRoute
  '/api/v1/attendance/today': typeof ApiV1AttendanceTodayRoute
  '/api/v1/delivery-partners/$id': typeof ApiV1DeliveryPartnersIdRoute
  '/api/v1/attendance': typeof ApiV1AttendanceIndexRoute
  '/api/v1/delivery-partners': typeof ApiV1DeliveryPartnersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/attendance/check-in': typeof ApiV1AttendanceCheckInRoute
  '/api/v1/attendance/check-out': typeof ApiV1AttendanceCheckOutRoute
  '/api/v1/attendance/today': typeof ApiV1AttendanceTodayRoute
  '/api/v1/delivery-partners/$id': typeof ApiV1DeliveryPartnersIdRoute
  '/api/v1/attendance/': typeof ApiV1AttendanceIndexRoute
  '/api/v1/delivery-partners/': typeof ApiV1DeliveryPartnersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/audit-logs'
    | '/dashboard'
    | '/deliveries'
    | '/earnings'
    | '/partners'
    | '/reports'
    | '/settings'
    | '/users'
    | '/api/v1/me'
    | '/api/v1/attendance/check-in'
    | '/api/v1/attendance/check-out'
    | '/api/v1/attendance/today'
    | '/api/v1/delivery-partners/$id'
    | '/api/v1/attendance/'
    | '/api/v1/delivery-partners/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/audit-logs'
    | '/dashboard'
    | '/deliveries'
    | '/earnings'
    | '/partners'
    | '/reports'
    | '/settings'
    | '/users'
    | '/api/v1/me'
    | '/api/v1/attendance/check-in'
    | '/api/v1/attendance/check-out'
    | '/api/v1/attendance/today'
    | '/api/v1/delivery-partners/$id'
    | '/api/v1/attendance'
    | '/api/v1/delivery-partners'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/deliveries'
    | '/_authenticated/earnings'
    | '/_authenticated/partners'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/api/v1/me'
    | '/api/v1/attendance/check-in'
    | '/api/v1/attendance/check-out'
    | '/api/v1/attendance/today'
    | '/api/v1/delivery-partners/$id'
    | '/api/v1/attendance/'
    | '/api/v1/delivery-partners/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1AttendanceCheckInRoute: typeof ApiV1AttendanceCheckInRoute
  ApiV1AttendanceCheckOutRoute: typeof ApiV1AttendanceCheckOutRoute
  ApiV1AttendanceTodayRoute: typeof ApiV1AttendanceTodayRoute
  ApiV1DeliveryPartnersIdRoute: typeof ApiV1DeliveryPartnersIdRoute
  ApiV1AttendanceIndexRoute: typeof ApiV1AttendanceIndexRoute
  ApiV1DeliveryPartnersIndexRoute: typeof ApiV1DeliveryPartnersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/delivery-partners/': {
      id: '/api/v1/delivery-partners/'
      path: '/api/v1/delivery-partners'
      fullPath: '/api/v1/delivery-partners/'
      preLoaderRoute: typeof ApiV1DeliveryPartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/attendance/': {
      id: '/api/v1/attendance/'
      path: '/api/v1/attendance'
      fullPath: '/api/v1/attendance/'
      preLoaderRoute: typeof ApiV1AttendanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/delivery-partners/$id': {
      id: '/api/v1/delivery-partners/$id'
      path: '/api/v1/delivery-partners/$id'
      fullPath: '/api/v1/delivery-partners/$id'
      preLoaderRoute: typeof ApiV1DeliveryPartnersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/attendance/today': {
      id: '/api/v1/attendance/today'
      path: '/api/v1/attendance/today'
      fullPath: '/api/v1/attendance/today'
      preLoaderRoute: typeof ApiV1AttendanceTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/attendance/check-out': {
      id: '/api/v1/attendance/check-out'
      path: '/api/v1/attendance/check-out'
      fullPath: '/api/v1/attendance/check-out'
      preLoaderRoute: typeof ApiV1AttendanceCheckOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/attendance/check-in': {
      id: '/api/v1/attendance/check-in'
      path: '/api/v1/attendance/check-in'
      fullPath: '/api/v1/attendance/check-in'
      preLoaderRoute: typeof ApiV1AttendanceCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1AttendanceCheckInRoute: ApiV1AttendanceCheckInRoute,
  ApiV1AttendanceCheckOutRoute: ApiV1AttendanceCheckOutRoute,
  ApiV1AttendanceTodayRoute: ApiV1AttendanceTodayRoute,
  ApiV1DeliveryPartnersIdRoute: ApiV1DeliveryPartnersIdRoute,
  ApiV1AttendanceIndexRoute: ApiV1AttendanceIndexRoute,
  ApiV1DeliveryPartnersIndexRoute: ApiV1DeliveryPartnersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
